// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKrxyl3Ock1Hi5F1hemQ8459zD4f1F4fQ',
    appId: '1:573116276939:web:83d5c1d960724aa351fb4e',
    messagingSenderId: '573116276939',
    projectId: 'moneymingle-f685f',
    authDomain: 'moneymingle-f685f.firebaseapp.com',
    storageBucket: 'moneymingle-f685f.firebasestorage.app',
    measurementId: 'G-RS0DEYWXKZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1XEoASgT8y2BwzvKtHWY8cu-EMi53YBc',
    appId: '1:573116276939:android:69c202b0b07e0f6b51fb4e',
    messagingSenderId: '573116276939',
    projectId: 'moneymingle-f685f',
    storageBucket: 'moneymingle-f685f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpEVqOWiIgAyQ38cLhnOPAXfmE5UEHMNs',
    appId: '1:573116276939:ios:22293970e3826a6c51fb4e',
    messagingSenderId: '573116276939',
    projectId: 'moneymingle-f685f',
    storageBucket: 'moneymingle-f685f.firebasestorage.app',
    iosBundleId: 'com.example.moneyMingle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpEVqOWiIgAyQ38cLhnOPAXfmE5UEHMNs',
    appId: '1:573116276939:ios:22293970e3826a6c51fb4e',
    messagingSenderId: '573116276939',
    projectId: 'moneymingle-f685f',
    storageBucket: 'moneymingle-f685f.firebasestorage.app',
    iosBundleId: 'com.example.moneyMingle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKrxyl3Ock1Hi5F1hemQ8459zD4f1F4fQ',
    appId: '1:573116276939:web:00547db6ff9e5c6651fb4e',
    messagingSenderId: '573116276939',
    projectId: 'moneymingle-f685f',
    authDomain: 'moneymingle-f685f.firebaseapp.com',
    storageBucket: 'moneymingle-f685f.firebasestorage.app',
    measurementId: 'G-31LBHEKFFB',
  );

}